SEED: 42 
data:
  data_folds: [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]   
  val_fold: 0   
  data_path: <path to mesh files> 
  output_path: <path to output directory> 
ssm:
  feat_size: 352
  n_points: 4000 
  n_points_inference: 2048
  n_jobs: 1 
  n_lbo_eigenfunctions: 20 
  scaling: [0.12, 0.12, 0.12]
  weights: null
  TrainingDetails:
    batch_size: 64
    lr: 0.0001 
    n_epochs: 30 
    n_sample_points: 2048
  TestingDetails:
    reference_shape: null
    variance_pmf:  1000 
